### ISSUE TITLE
Another similar project: Sample Font Repository

### ISSUE THREAD

**Issue by raphaelbastide** [unified-font-repository/Unified-Font-Repository#23]
@djrrb made a great work here to adapt the font project architecture to a modern work flow.
https://github.com/djrrb/Sample-Font-Repository
Maybe we can consider merging the projects as Unified Font Repository is more popular but lacks of detail, completeness.

**Comment by djrrb** [comment]
Hi @raphaelbastide! I love your repository format, and would be happy to join forces or contribute what I have done if it would be helpful.

I published this sample for myself and my colleagues, and there are a few quirks in my approach which you may or may not want to incorporate into a more public-facing repository. I'm happy to discuss the best approach.

Let me know how you want to proceed!

**Comment by pathumego** [comment]
@raphaelbastide Can we discuss this? I think @djrrb s work actually adds some much needed updates. I am listing here the @djrrb s additions for discussion. We will have to discuss weather we add these elements to the UFR and how. 

- Updates to `METADATA.yml`
       - `project status` (values;released, gamma, beta, alpha)
- Adding `./dist`
- Adding `./scripts`
- Adding `./website`
- Additions to `./sources`
       - `/sources/features`
       -  `/sources/2-build`
       -  Removed `sources/2-0tf`, `sources/3-ttf`
- Adding `./specimen.png` This was partially discussed in #2
- Detailed `README.md`

**Comment by raphaelbastide** [comment]
@pathumego I agree with you but isn’t it more straightforward to redirect people on @djrrb’s Sample Font Repository directly, as I don’t plan tot maintain actively UFR. I am open to both solutions. What do you think?

**Comment by pathumego** [comment]
> it more straightforward to redirect people on @djrrb’s Sample Font Repository

Well the issue with this was pointed out by him;

> I published this sample for myself and my colleagues, and there are a few quirks in my approach which you may or may not want to incorporate into a more public-facing repository.

So, Sample Font Repository is more of a best practices from a established type designer rather than a standard. Which is really useful. But UFR was born to address the standardization and I think it's importance has only increased with git based workflow becoming the industry standard. A redirection to Sample Font Repository will indicate that UFR as a `standard` is deprecated, or as you mentioned not-maintained. I think that should not happen :)

>  I don’t plan to maintain actively UFR

That is sad! This is because of your intentions for UTD as discussed in #13? I personally think UFR is a really cool project with actual use. And Sample Font Repository repo is an indication of importance of this project and an need for an update. UFR could use some updates and maybe addressing the issues from around 2013 when the discussion was active.

I can simply send some PRs with @djrrb s changes. Those might warrant a version bump to `0.3` or higher. 

OR,

Since you are not planning to maintain further actively, there are two things you can do.
- Appointing new maintainers (I am willing. Maybe @djrrb and @davelab6  if they are interested)
- Setting up a new home for the project, and appointing new maintainers 
     1. We can setup a GitHub org (https://github.com/unified-font-repository is available)

I prefer the option i. Which will give the project a face of a community effort. And also let us setup other repositories for tools or related things in the future. In that case we have two options to migrate.
     1.  Fork the repo; This will not migrate the issues and history, only the commit history.
     2. Or transfer the ownership to the new GH org from the `settings`; This will migrate the whole repo along with the issues and Github will automatically redirect all the repository links. More [here](https://help.github.com/articles/about-repository-transfers/)

I hope `maintain actively` dose not mean contributions :) This setup will actually make your life easier as a maintainer. I can line-up a few PRs and ping you when they are ready for review :) 
Version `0.3` could be released with the new org.
 
I love this project and hope we can keep it alive :)

**Comment by raphaelbastide** [comment]
Thank you for your ideas and support @pathumego.
I am happy to learn that interesting solutions to this case exist and I appreciate your help pointing the different aspects of those possible futures.

> A redirection to Sample Font Repository will indicate that UFR as a 'standard' is deprecated, or as you mentioned not-maintained. I think that should not happen :)

I agree.

> I can simply send some PRs with @djrrb s changes […] Version 0.3 could be released with the new org.

I’ll be happy to accept your PR, and I think that GH org is an elegant solution, and the best possible for the future of this project. Let me know when your PR is ready and let’s make UFR a organisation after  `0.3`!

**Comment by raphaelbastide** [comment]
The version has been updated to `0.3`. The project is ready for to be transferred to an organisation. Should I create it myself?

**Comment by pathumego** [comment]
Yes please, you can use the `unified-font-repository` as the username.

**Comment by raphaelbastide** [comment]
The project has been transfered to https://github.com/unified-font-repository/Unified-Font-Repository.
Feel free to invite contributors. I am closing this issue.
